In [37]:
import pandas as pd
pd.options.mode.chained_assignment = None
import numpy as np
from scipy import stats
from datetime import date, datetime, timedelta

import seaborn as sns
import matplotlib.pyplot as plt

from io import BytesIO
import base64
from IPython.core.display import HTML

In [88]:
df=pd.read_csv('DOB_Violations_20260301.csv')
df

,ISN_DOB_BIS_VIOL,BORO,BIN,BLOCK,LOT,ISSUE_DATE,VIOLATION_TYPE_CODE,VIOLATION_NUMBER,HOUSE_NUMBER,STREET,DISPOSITION_DATE,DISPOSITION_COMMENTS,DEVICE_NUMBER,DESCRIPTION,ECB_NUMBER,NUMBER,VIOLATION_CATEGORY,VIOLATION_TYPE
0,2787713,3,3041236,1519,29,20250109,IMEGNCY,18938,298,MARION STREET,20250304.0,"DISMISSED, SIDEWALK SHED ERECTED",NaN,INSTALL A SIDEWALK SHED APPROXIMATED 20 FEET A...,NaN,V*010925IMEGNCY18938,V*-DOB VIOLATION - DISMISSED,IMEGNCY-IMMEDIATE EMERGENCY ...
1,2788952,2,2114613,2379,7,20250122,AEUHAZ1,00175,404,EAST 158 STREET,20251031.0,ECB DISMISSED,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,39130865H,V*012225AEUHAZ100175,V*-DOB VIOLATION - DISMISSED,AEUHAZ1-FAIL TO CERTIFY CLASS 1 ...
2,2795652,3,3074129,3257,5,20251031,EGNCY,19716,201,WILSON AVENUE,NaN,NaN,NaN,FULLY DEMOLISH THE BUILDING AND GRADE & FENCE ...,NaN,V103125EGNCY19716,V-DOB VIOLATION - ACTIVE,EGNCY-EMERGENCY ...
3,2795216,4,4170046,8176,18,20251013,C,25-02318,53-24,241 STREET,20251031.0,OKAY TO DISMISS DOB VIO AS PER INSP BADGE ...,NaN,STRUCTURE RENDERED NON-COMPLIANT. AT TIME OF I...,NaN,V*101325C25-02318,V*-DOB VIOLATION - DISMISSED,C-CONSTRUCTION ...
4,2794799,1,1010145,590,29,20250926,IMEGNCY,19603,168,WEST 4 STREET,20251105.0,IED IS RESOLVED. WORK COMPLETED BY OWNERAND VE...,NaN,PROVIDE APPROXIMATELY 20 LINEAR FEET OF SIDEWA...,NaN,V*092625IMEGNCY19603,V*-DOB VIOLATION - DISMISSED,IMEGNCY-IMMEDIATE EMERGENCY ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29405,2816606,3,3023365,1033,43,20251118,C,SR0601NS,526,4 AVENUE,20260227.0,"NAN, BUILDING DEMOLISHED",NaN,FAILURE TO MAINTAIN BUILDING IN CODE COMPLIANT...,NaN,V*111825CSR0601NS,V*-DOB VIOLATION - DISMISSED,C-CONSTRUCTION ...
29406,2808548,3,3125915,5368,2,20251114,LBLVIO,12896,3619,15 AVENUE,20260227.0,CIANOW CRM Violation Dismissed,00038189,VIOLATION ISSUED-FAILURE TO FILE 2024 EXTERNAL...,NaN,V*111425LBLVIO12896,V*-DOB VIOLATION - DISMISSED,LBLVIO-LOW PRESSURE BOILER ...
29407,2793480,1,1006165,445,4,20250725,LANDMK,26-0087,60,2 AVENUE,20260227.0,NaN,NaN,NaN,NaN,V*072525LANDMK26-0087,V*-DOB VIOLATION - DISMISSED,LANDMK-LANDMARK ...
29408,2798651,1,1027008,1077,12,20251114,LBLVIO,02999,533,WEST 48 STREET,20260227.0,CIANOW CRM Violation Dismissed,00082955,VIOLATION ISSUED-FAILURE TO FILE 2024 EXTERNAL...,NaN,V*111425LBLVIO02999,V*-DOB VIOLATION - DISMISSED,LBLVIO-LOW PRESSURE BOILER ...
29409,2811653,4,4007724,596,33,20251114,LBLVIO,16001,26-17,28 STREET,20260227.0,CIANOW CRM Violation Dismissed,00160074,VIOLATION ISSUED-FAILURE TO FILE 2024 EXTERNAL...,NaN,V*111425LBLVIO16001,V*-DOB VIOLATION - DISMISSED,LBLVIO-LOW PRESSURE BOILER ...

In [3]:
df.columns

Index(['ISN_DOB_BIS_VIOL', 'BORO', 'BIN', 'BLOCK', 'LOT', 'ISSUE_DATE',
       'VIOLATION_TYPE_CODE', 'VIOLATION_NUMBER', 'HOUSE_NUMBER', 'STREET',
       'DISPOSITION_DATE', 'DISPOSITION_COMMENTS', 'DEVICE_NUMBER',
       'DESCRIPTION', 'ECB_NUMBER', 'NUMBER', 'VIOLATION_CATEGORY',
       'VIOLATION_TYPE'],
      dtype='object')

In [7]:
df.groupby(['VIOLATION_TYPE']).VIOLATION_TYPE.count()

VIOLATION_TYPE
AEUHAZ1-FAIL TO CERTIFY CLASS 1                                         NONE                 1095
B-BOILER                                                          BOILER  OPTIONAL              1
C-CONSTRUCTION                                                    OTHER   OPTIONAL           5776
CLOS-PADLOCK                                                         NONE                      27
E-ELEVATOR                                                        ELEVATORREQUIRED             30
EGNCY-EMERGENCY                                                       NONE                     49
EGRADE-FAILURE TO POST ENERGY GRADE/SCORE                              NONE                     2
FISPFCS-FAILURE TO CORRECT SWARMP CONDITIONS (FACADE)                   FACADE  REQUIRED       83
FISPHAZ-HAZARDOUS CONDITION (FACADE)                                    FACADE  REQUIRED       84
FISPNRF-NO REPORT AND / OR LATE FILING (FACADE)                         FACADE  REQUIRED        1
HBLVIO-HIGH PRESSURE BOILER                                            BOILER  REQUIRED      1648
IMEGNCY-IMMEDIATE EMERGENCY                                             ANYTHINGOPTIONAL      848
LANDMK-LANDMARK                                                        NONE                   527
LBLVIO-LOW PRESSURE BOILER                                             BOILER  REQUIRED     18473
P-PLUMBING                                                        NONE                        613
UB-UNSAFE BUILDINGS                                                NONE                       119
Z-ZONING                                                          NONE                         34
Name: VIOLATION_TYPE, dtype: int64

In [9]:
df.ISSUE_DATE

0        20250109
1        20250122
2        20251031
3        20251013
4        20250926
           ...
29405    20251118
29406    20251114
29407    20250725
29408    20251114
29409    20251114
Name: ISSUE_DATE, Length: 29410, dtype: int64

In [11]:
df.dtypes

ISN_DOB_BIS_VIOL          int64
BORO                      int64
BIN                       int64
BLOCK                     int64
LOT                       int64
ISSUE_DATE                int64
VIOLATION_TYPE_CODE      object
VIOLATION_NUMBER         object
HOUSE_NUMBER             object
STREET                   object
DISPOSITION_DATE        float64
DISPOSITION_COMMENTS     object
DEVICE_NUMBER            object
DESCRIPTION              object
ECB_NUMBER               object
NUMBER                   object
VIOLATION_CATEGORY       object
VIOLATION_TYPE           object
dtype: object

In [90]:
df.ISSUE_DATE = pd.to_datetime(df.ISSUE_DATE, format='%Y%m%d')

In [91]:
df.dtypes

ISN_DOB_BIS_VIOL                 int64
BORO                             int64
BIN                              int64
BLOCK                            int64
LOT                              int64
ISSUE_DATE              datetime64[ns]
VIOLATION_TYPE_CODE             object
VIOLATION_NUMBER                object
HOUSE_NUMBER                    object
STREET                          object
DISPOSITION_DATE               float64
DISPOSITION_COMMENTS            object
DEVICE_NUMBER                   object
DESCRIPTION                     object
ECB_NUMBER                      object
NUMBER                          object
VIOLATION_CATEGORY              object
VIOLATION_TYPE                  object
dtype: object

In [92]:
for index, row in df.head().iterrows():
    print(row.ISSUE_DATE.strftime("%B"), row.ISSUE_DATE.month)

January 1
January 1
October 10
October 10
September 9

In [93]:
month=[m.strftime("%B") for m in df.ISSUE_DATE]

In [94]:
df['issue_month']=month
df

,ISN_DOB_BIS_VIOL,BORO,BIN,BLOCK,LOT,ISSUE_DATE,VIOLATION_TYPE_CODE,VIOLATION_NUMBER,HOUSE_NUMBER,STREET,DISPOSITION_DATE,DISPOSITION_COMMENTS,DEVICE_NUMBER,DESCRIPTION,ECB_NUMBER,NUMBER,VIOLATION_CATEGORY,VIOLATION_TYPE,issue_month
0,2787713,3,3041236,1519,29,2025-01-09,IMEGNCY,18938,298,MARION STREET,20250304.0,"DISMISSED, SIDEWALK SHED ERECTED",NaN,INSTALL A SIDEWALK SHED APPROXIMATED 20 FEET A...,NaN,V*010925IMEGNCY18938,V*-DOB VIOLATION - DISMISSED,IMEGNCY-IMMEDIATE EMERGENCY ...,January
1,2788952,2,2114613,2379,7,2025-01-22,AEUHAZ1,00175,404,EAST 158 STREET,20251031.0,ECB DISMISSED,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,39130865H,V*012225AEUHAZ100175,V*-DOB VIOLATION - DISMISSED,AEUHAZ1-FAIL TO CERTIFY CLASS 1 ...,January
2,2795652,3,3074129,3257,5,2025-10-31,EGNCY,19716,201,WILSON AVENUE,NaN,NaN,NaN,FULLY DEMOLISH THE BUILDING AND GRADE & FENCE ...,NaN,V103125EGNCY19716,V-DOB VIOLATION - ACTIVE,EGNCY-EMERGENCY ...,October
3,2795216,4,4170046,8176,18,2025-10-13,C,25-02318,53-24,241 STREET,20251031.0,OKAY TO DISMISS DOB VIO AS PER INSP BADGE ...,NaN,STRUCTURE RENDERED NON-COMPLIANT. AT TIME OF I...,NaN,V*101325C25-02318,V*-DOB VIOLATION - DISMISSED,C-CONSTRUCTION ...,October
4,2794799,1,1010145,590,29,2025-09-26,IMEGNCY,19603,168,WEST 4 STREET,20251105.0,IED IS RESOLVED. WORK COMPLETED BY OWNERAND VE...,NaN,PROVIDE APPROXIMATELY 20 LINEAR FEET OF SIDEWA...,NaN,V*092625IMEGNCY19603,V*-DOB VIOLATION - DISMISSED,IMEGNCY-IMMEDIATE EMERGENCY ...,September
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29405,2816606,3,3023365,1033,43,2025-11-18,C,SR0601NS,526,4 AVENUE,20260227.0,"NAN, BUILDING DEMOLISHED",NaN,FAILURE TO MAINTAIN BUILDING IN CODE COMPLIANT...,NaN,V*111825CSR0601NS,V*-DOB VIOLATION - DISMISSED,C-CONSTRUCTION ...,November
29406,2808548,3,3125915,5368,2,2025-11-14,LBLVIO,12896,3619,15 AVENUE,20260227.0,CIANOW CRM Violation Dismissed,00038189,VIOLATION ISSUED-FAILURE TO FILE 2024 EXTERNAL...,NaN,V*111425LBLVIO12896,V*-DOB VIOLATION - DISMISSED,LBLVIO-LOW PRESSURE BOILER ...,November
29407,2793480,1,1006165,445,4,2025-07-25,LANDMK,26-0087,60,2 AVENUE,20260227.0,NaN,NaN,NaN,NaN,V*072525LANDMK26-0087,V*-DOB VIOLATION - DISMISSED,LANDMK-LANDMARK ...,July
29408,2798651,1,1027008,1077,12,2025-11-14,LBLVIO,02999,533,WEST 48 STREET,20260227.0,CIANOW CRM Violation Dismissed,00082955,VIOLATION ISSUED-FAILURE TO FILE 2024 EXTERNAL...,NaN,V*111425LBLVIO02999,V*-DOB VIOLATION - DISMISSED,LBLVIO-LOW PRESSURE BOILER ...,November
29409,2811653,4,4007724,596,33,2025-11-14,LBLVIO,16001,26-17,28 STREET,20260227.0,CIANOW CRM Violation Dismissed,00160074,VIOLATION ISSUED-FAILURE TO FILE 2024 EXTERNAL...,NaN,V*111425LBLVIO16001,V*-DOB VIOLATION - DISMISSED,LBLVIO-LOW PRESSURE BOILER ...,November

In [95]:
boro={1:'Manhattan', 
      2:'Bronx', 
      3:'Brooklyn',
      4:'Queens', 
      5:'Staten Island'}
df['boro_name']=df.BORO.map(boro)
df

,ISN_DOB_BIS_VIOL,BORO,BIN,BLOCK,LOT,ISSUE_DATE,VIOLATION_TYPE_CODE,VIOLATION_NUMBER,HOUSE_NUMBER,STREET,DISPOSITION_DATE,DISPOSITION_COMMENTS,DEVICE_NUMBER,DESCRIPTION,ECB_NUMBER,NUMBER,VIOLATION_CATEGORY,VIOLATION_TYPE,issue_month,boro_name
0,2787713,3,3041236,1519,29,2025-01-09,IMEGNCY,18938,298,MARION STREET,20250304.0,"DISMISSED, SIDEWALK SHED ERECTED",NaN,INSTALL A SIDEWALK SHED APPROXIMATED 20 FEET A...,NaN,V*010925IMEGNCY18938,V*-DOB VIOLATION - DISMISSED,IMEGNCY-IMMEDIATE EMERGENCY ...,January,Brooklyn
1,2788952,2,2114613,2379,7,2025-01-22,AEUHAZ1,00175,404,EAST 158 STREET,20251031.0,ECB DISMISSED,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,39130865H,V*012225AEUHAZ100175,V*-DOB VIOLATION - DISMISSED,AEUHAZ1-FAIL TO CERTIFY CLASS 1 ...,January,Bronx
2,2795652,3,3074129,3257,5,2025-10-31,EGNCY,19716,201,WILSON AVENUE,NaN,NaN,NaN,FULLY DEMOLISH THE BUILDING AND GRADE & FENCE ...,NaN,V103125EGNCY19716,V-DOB VIOLATION - ACTIVE,EGNCY-EMERGENCY ...,October,Brooklyn
3,2795216,4,4170046,8176,18,2025-10-13,C,25-02318,53-24,241 STREET,20251031.0,OKAY TO DISMISS DOB VIO AS PER INSP BADGE ...,NaN,STRUCTURE RENDERED NON-COMPLIANT. AT TIME OF I...,NaN,V*101325C25-02318,V*-DOB VIOLATION - DISMISSED,C-CONSTRUCTION ...,October,Queens
4,2794799,1,1010145,590,29,2025-09-26,IMEGNCY,19603,168,WEST 4 STREET,20251105.0,IED IS RESOLVED. WORK COMPLETED BY OWNERAND VE...,NaN,PROVIDE APPROXIMATELY 20 LINEAR FEET OF SIDEWA...,NaN,V*092625IMEGNCY19603,V*-DOB VIOLATION - DISMISSED,IMEGNCY-IMMEDIATE EMERGENCY ...,September,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29405,2816606,3,3023365,1033,43,2025-11-18,C,SR0601NS,526,4 AVENUE,20260227.0,"NAN, BUILDING DEMOLISHED",NaN,FAILURE TO MAINTAIN BUILDING IN CODE COMPLIANT...,NaN,V*111825CSR0601NS,V*-DOB VIOLATION - DISMISSED,C-CONSTRUCTION ...,November,Brooklyn
29406,2808548,3,3125915,5368,2,2025-11-14,LBLVIO,12896,3619,15 AVENUE,20260227.0,CIANOW CRM Violation Dismissed,00038189,VIOLATION ISSUED-FAILURE TO FILE 2024 EXTERNAL...,NaN,V*111425LBLVIO12896,V*-DOB VIOLATION - DISMISSED,LBLVIO-LOW PRESSURE BOILER ...,November,Brooklyn
29407,2793480,1,1006165,445,4,2025-07-25,LANDMK,26-0087,60,2 AVENUE,20260227.0,NaN,NaN,NaN,NaN,V*072525LANDMK26-0087,V*-DOB VIOLATION - DISMISSED,LANDMK-LANDMARK ...,July,Manhattan
29408,2798651,1,1027008,1077,12,2025-11-14,LBLVIO,02999,533,WEST 48 STREET,20260227.0,CIANOW CRM Violation Dismissed,00082955,VIOLATION ISSUED-FAILURE TO FILE 2024 EXTERNAL...,NaN,V*111425LBLVIO02999,V*-DOB VIOLATION - DISMISSED,LBLVIO-LOW PRESSURE BOILER ...,November,Manhattan
29409,2811653,4,4007724,596,33,2025-11-14,LBLVIO,16001,26-17,28 STREET,20260227.0,CIANOW CRM Violation Dismissed,00160074,VIOLATION ISSUED-FAILURE TO FILE 2024 EXTERNAL...,NaN,V*111425LBLVIO16001,V*-DOB VIOLATION - DISMISSED,LBLVIO-LOW PRESSURE BOILER ...,November,Queens

In [114]:
df_grouped=df.loc[df.VIOLATION_TYPE_CODE=='IMEGNCY'].groupby(['boro_name', 'issue_month']).ISN_DOB_BIS_VIOL.count().reset_index(name='violation_count')
df_grouped

        boro_name issue_month  violation_count
0           Bronx       April               11
1           Bronx      August               14
2           Bronx    December               20
3           Bronx    February               13
4           Bronx     January                5
5           Bronx        July                9
6           Bronx        June               12
7           Bronx       March               14
8           Bronx         May               12
9           Bronx    November                8
10          Bronx     October               13
11          Bronx   September               13
12       Brooklyn       April               25
13       Brooklyn      August               40
14       Brooklyn    December               32
15       Brooklyn    February               18
16       Brooklyn     January               29
17       Brooklyn        July               28
18       Brooklyn        June               30
19       Brooklyn       March               15
20       Brooklyn         May               22
21       Brooklyn    November               16
22       Brooklyn     October               48
23       Brooklyn   September               29
24      Manhattan       April               12
25      Manhattan      August               17
26      Manhattan    December               17
27      Manhattan    February                7
28      Manhattan     January               11
29      Manhattan        July                7
30      Manhattan        June                2
31      Manhattan       March               10
32      Manhattan         May               12
33      Manhattan    November               11
34      Manhattan     October               16
35      Manhattan   September               12
36         Queens       April               20
37         Queens      August               15
38         Queens    December               27
39         Queens    February                4
40         Queens     January                5
41         Queens        July               15
42         Queens        June               12
43         Queens       March               10
44         Queens         May               12
45         Queens    November               16
46         Queens     October               19
47         Queens   September               29
48  Staten Island       April                7
49  Staten Island      August                3
50  Staten Island    December                6
51  Staten Island    February                2
52  Staten Island     January                5
53  Staten Island        July                7
54  Staten Island        June                5
55  Staten Island       March                7
56  Staten Island         May                2
57  Staten Island    November                3
58  Staten Island     October                4
59  Staten Island   September                3

In [420]:
months=['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
df_table=pd.DataFrame(columns=['boro']+months)

for b in df_grouped.boro_name.unique():
    row=[b]
    for m in months:
        c=df_grouped.loc[(df_grouped.boro_name==b) & (df_grouped.issue_month==m)].violation_count.values[0]
        row.append(c)
    df_table.loc[len(df_table)]=row
total_row=['Total']
for m in months:
    month_total=df_table[m].sum()
    total_row.append(month_total)
df_table.loc[len(df_table)]=total_row

df_table=df_table.set_index('boro')#.index_name('')
df_table.index.name=None
df_table

,January,February,March,April,May,June,July,August,September,October,November,December
Bronx,5,13,14,11,12,12,9,14,13,13,8,20
Brooklyn,29,18,15,25,22,30,28,40,29,48,16,32
Manhattan,11,7,10,12,12,2,7,17,12,16,11,17
Queens,5,4,10,20,12,12,15,15,29,19,16,27
Staten Island,5,2,7,7,2,5,7,3,3,4,3,6
Total,55,44,56,75,60,61,66,89,86,100,54,102

# Add Sparklines

In [421]:
def sparkline(data):
    fig, ax = plt.subplots(1, 1, figsize=(4, 0.3))
    ax.plot(data)
    
    ax.set_axis_off()
    ax.fill_between(range(len(data)), data, len(data)*[min(data)], alpha=0.1)
   
    max_val = np.max(data) # Find the maximum value
    max_indices = np.argwhere(data == max_val)

    for i, y in zip(max_indices, np.array([y for i, y in enumerate(data) if i in max_indices])):
        ax.plot(i[0], y,  marker='.', color='#0072b5ff')
    
    min_val = np.min(data) # Find the maximum value
    min_indices = np.argwhere(data == min_val)

    for i, y in zip(min_indices, np.array([y for i, y in enumerate(data) if i in min_indices])):
        ax.plot(i[0], y,  marker='.', color='#bc3c29ff')
    
    #ax.plot(np.argmax(data), data[np.argmax(data)],  marker='.', color='#0072b5ff')
    #ax.plot(np.argmin(data), data[np.argmin(data)], marker='.', color='#bc3c29ff')

    img = BytesIO()
    plt.savefig(img)
    img.seek(0)
    plt.close()
    
    return '<img src="data:image/png;base64,{}"/>'.format(base64.b64encode(img.read()).decode())

In [422]:
df_table['sparkline_data']=df_table[months].values.tolist()
df_table

,January,February,March,April,May,June,July,August,September,October,November,December,sparkline_data
Bronx,5,13,14,11,12,12,9,14,13,13,8,20,"[5, 13, 14, 11, 12, 12, 9, 14, 13, 13, 8, 20]"
Brooklyn,29,18,15,25,22,30,28,40,29,48,16,32,"[29, 18, 15, 25, 22, 30, 28, 40, 29, 48, 16, 32]"
Manhattan,11,7,10,12,12,2,7,17,12,16,11,17,"[11, 7, 10, 12, 12, 2, 7, 17, 12, 16, 11, 17]"
Queens,5,4,10,20,12,12,15,15,29,19,16,27,"[5, 4, 10, 20, 12, 12, 15, 15, 29, 19, 16, 27]"
Staten Island,5,2,7,7,2,5,7,3,3,4,3,6,"[5, 2, 7, 7, 2, 5, 7, 3, 3, 4, 3, 6]"
Total,55,44,56,75,60,61,66,89,86,100,54,102,"[55, 44, 56, 75, 60, 61, 66, 89, 86, 100, 54, ..."

In [423]:
df_table[''] = df_table['sparkline_data'].map(sparkline)

In [419]:
#HTML(df_table.loc[:,df_table.columns !='sparkline_data'].to_html(escape=False))

In [424]:
df_table.style

In [425]:
def bold_max(s, props=''):
    """
    Highlights the maximum value in a Series with a given CSS property.
    """
    is_max = s == s.max()
    return [props if v else '' for v in is_max]

def bold_min(s, props=''):
    """
    Highlights the maximum value in a Series with a given CSS property.
    """
    is_max = s == s.min()
    return [props if v else '' for v in is_max]
    
df_table=df_table.loc[:,df_table.columns !='sparkline_data'].style.apply(bold_max, props='font-weight: bold;color:#0072b5ff', axis=1, subset=months)
df_table=df_table.apply(bold_min, props='font-weight: bold;color:#bc3c29ff', axis=1, subset=months)

df_table

In [426]:
def add_vertical_border(column):
    # Apply a right border to a specific column, for example 'Col_B'
    if column.name in months:
        return ['border-right: 2px solid black'] * len(column)
    return [''] * len(column)

df_table=df_table.apply(add_vertical_border, axis=0)
df_table

In [427]:
rows_to_border = ['Bronx', 'Total']

# 2. Define the styling function
def highlight_rows_with_border(s):
    """
    Applies a bottom border to all cells in specific rows.
    's' is a Series representing values from one column.
    """
    # Create a list of CSS styles for each cell in the column
    is_bordered = s.index.isin(rows_to_border)
    
    # CSS for the bottom border
    border_style = 'border-top: 2px solid black;'
    
    # Apply border only to the desired rows, otherwise apply no style
    return [border_style if condition else '' for condition in is_bordered]

In [428]:
# 3. Apply the function across columns (axis=1) to style the entire row's cells
df_table.apply(highlight_rows_with_border, axis=0)