In [1]:
import pandas as pd

In [10]:
df2011=pd.DataFrame(columns=['census_tract', 'median income'])
df2011.loc[len(df2011)]=['a', 32000]
df2011.loc[len(df2011)]=['b', 50000]
df2011.loc[len(df2011)]=['c', 80000]
df2011.loc[len(df2011)]=['d', 100000]

df2011['year']='2011'

df2011

  census_tract  median income  year
0            a          32000  2011
1            b          50000  2011
2            c          80000  2011
3            d         100000  2011

In [11]:
df2012=pd.DataFrame(columns=['census_tract', 'median income'])
df2012.loc[len(df2012)]=['a', 34000]
df2012.loc[len(df2012)]=['b', 52000]
df2012.loc[len(df2012)]=['c', 83000]
df2012.loc[len(df2012)]=['d', 110000]

df2012['year']='2012'

df2012

  census_tract  median income  year
0            a          34000  2012
1            b          52000  2012
2            c          83000  2012
3            d         110000  2012

In [12]:
df_concat=pd.concat([df2011, df2012])

df_concat

  census_tract  median income  year
0            a          32000  2011
1            b          50000  2011
2            c          80000  2011
3            d         100000  2011
0            a          34000  2012
1            b          52000  2012
2            c          83000  2012
3            d         110000  2012